
import dspy
from dspy.teleprompt import BootstrapFewShot
from devops_agent.agent_module import DevOpsAgent
from devops_agent.dspy_client import init_dspy_lms
import json
import os

def validate_tool_usage(gold, pred, trace=None):
    """
    Metric to check if the predicted tool calls match the expected ones.
    """
    if not hasattr(pred, "tool_calls"):
        return False
        
    # Simple strict equality for now. 
    # In the future we might handle argument permutation or partial matches.
    # But since these are synthetic examples generated by the same agent logic, 
    # strict equality is a reasonable baseline.
    return gold.tool_calls == pred.tool_calls

def optimize_agent():
    print("🧠 Initializing Optimization Pipeline...")
    _, teacher_lm = init_dspy_lms() # Use smart model for optimization reasoning
    
    # 1. Load Synthetic Data
    data_path = "devops_agent/data/synthetic_examples.json"
    if not os.path.exists(data_path):
        print(f"❌ Error: Synthetic data not found at {data_path}")
        return

    print(f"📂 Loading training data from {data_path}...")
    with open(data_path, "r") as f:
        raw_data = json.load(f)

    # Convert to dspy.Example
    from devops_agent.tool_indexer import get_all_tools
    all_tools = get_all_tools()
    
    trainset = []
    for item in raw_data:
        ex = dspy.Example(
            query=item["query"],
            tools_schema=all_tools,
            history=[], # Start with empty history for sync traces
            tool_calls=item["tool_calls"],
            rationale=item["rationale"] # Using this as ground truth/hint
        ).with_inputs("query", "tools_schema", "history")
        trainset.append(ex)

    print(f"📊 Loaded {len(trainset)} training examples.")

    # 2. Configure Optimizer
    # We use BootstrapFewShot which is robust for self-correction and few-shot selection
    teleprompter = BootstrapFewShot(
        metric=validate_tool_usage,
        max_bootstrapped_demos=4,       # Few-shot examples to pick
        max_labeled_demos=4,
        max_rounds=1,                   # Iterations
    )

    # 3. Compiling
    print("🚀 Compiling Agent (this involves running the agent against the training set)...")
    # We compile the DevOpsAgent module
    # Note: DevOpsAgent() creates a fresh instance. 
    # Ideally we should use the same class structure as the runtime one.
    student = DevOpsAgent()
    
    # Run compilation
    # The teacher needs to be the smart model to assess/generate examples?? 
    # Actually BootstrapFewShot uses the `dspy.settings.lm` if not specified.
    # Ensuring we have the smart model as default during optimization.
    with dspy.context(lm=teacher_lm):
        compiled_agent = teleprompter.compile(student, trainset=trainset)

    # 4. Save
    output_path = "devops_agent/compiled_agent.json"
    print(f"💾 Saving compiled agent to {output_path}...")
    compiled_agent.save(output_path)
    print("✅ Optimization Complete!")

if __name__ == "__main__":
    optimize_agent()
